[package]
name = "eprom5vread"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = { version = "0.7" }
paste = { version = "1.0" }
stm32g0b0 = { path = "../stm32g0b0", features = ["critical-section"] }
