[package]
name = "stm32g0b0"
version = "0.1.0"
edition = "2021"

[features]
critical-section = ["dep:critical-section"]

[dependencies]
cortex-m = { version = "0.7" }
critical-section = { version = "1.1", optional = true }
vcell = { version = "0.1" }
